apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: bluegreen-namespace
spec:
  selector:
    app: consumer
  type: ClusterIP
  ports:
    - name: tcp-port
      port: 8081
      targetPort: 8081
