apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: bluegreen-namespace
spec:
  selector:
    app: producer
  type: ClusterIP
  ports:
    - name: tcp-port
      port: 8080
      targetPort: 8080
